### ISSUE TITLE
Update codebase and make necessary changes

### ISSUE THREAD

**Issue by juhiechandra** [OWASP/RiskAssessmentFramework#71]
**Description:**
The current codebase is outdated and needs to be updated to ensure compatibility with the latest technologies and security standards. I will recheck the codebase and make the necessary changes along with mentor. This will include:

1. Update all dependencies and packages to the latest versions
2. Check for any security vulnerabilities and fix them
3. Refactor any deprecated code
4. Remove any unused code
5. Improve code readability and maintainability

**Tasks:**

- [ ] Recheck the codebase to identify outdated packages and dependencies
- [ ] Update all packages and dependencies to the latest versions
- [ ] Check for any security vulnerabilities and fix them
- [ ] Refactor any deprecated code
- [ ] Remove any unused code
- [ ] Improve code readability and maintainability
- [ ] Test the updated codebase to ensure that everything is working as expected
- [ ] Document the changes made in the codebase

This issue was filed after discussing potential changes with @azharanees, GSoC'19 under RAF project.

**Comment by juhiechandra** [comment]
Note: To pick up this item later

**Comment by msbatin** [comment]
0001-Refactor-codebase.patch
0002-Update-documentation.patch
0003-Improve-testing-suite.patch

**Comment by msbatin** [comment]
0001-Refactor-codebase.patch
0002-Update-documentation.patch
0003-Improve-testing-suite.patch
[](url)
