### ISSUE TITLE
Add Loading Spinner to Angular Web App

### ISSUE THREAD

**Issue by juhiechandra** [OWASP/RiskAssessmentFramework#72]
**Description:**
As a contributor, I want to see a loading spinner when the web app is loading so that I know the page is still loading and not frozen.

**Tasks:**
- [ ] Create a loading spinner component.
- [ ] Use a popular UI library such as Bootstrap or Material UI, or create a custom component. 
- [ ] Add appropriate animations and styles to make it visually appealing.
- [ ] Implement the loading spinner in the app.

**My Steps:**
- [ ] Verify that the loading spinner displays and hides correctly.
- [ ] Test the spinner with various network conditions (e.g. slow network speeds).
- [ ] Include screenshots or gifs of the spinner in action.
- [ ] Seek approval from team members.

**Feedback from existing codebase:**
Use Material UI of Angular.
However as this library is 5 years old, team can certainly decide to use a new UI library.

**Comment by juhiechandra** [comment]
Note: To pick up this item later
